// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
// ignore: depend_on_referenced_packages
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBIurrfIFiU3tn_eCxhf34cZlgp9EOFx5k',
    appId: '1:968838365814:web:2386a19511e3c89b995557',
    messagingSenderId: '968838365814',
    projectId: 'funnychuck-2099d',
    authDomain: 'funnychuck-2099d.firebaseapp.com',
    storageBucket: 'funnychuck-2099d.appspot.com',
    measurementId: 'G-691ZC87MEJ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCEZC_JpeBHUy1zYbcMIzbebnW4neBumCM',
    appId: '1:968838365814:android:c1d72f28c69b0f58995557',
    messagingSenderId: '968838365814',
    projectId: 'funnychuck-2099d',
    storageBucket: 'funnychuck-2099d.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCQQD7DOEUvUjNbQ5exY7AwHDah0JvepVE',
    appId: '1:968838365814:ios:495c53044a612e72995557',
    messagingSenderId: '968838365814',
    projectId: 'funnychuck-2099d',
    storageBucket: 'funnychuck-2099d.appspot.com',
    iosClientId:
        '968838365814-tkq05n89robp9ren653rfd1kivv1tsee.apps.googleusercontent.com',
    iosBundleId: 'com.example.funnyChuck',
  );
}
